replicaCount: 1

image:
  repository: yishaigalili/rickmorty-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30007


livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
