apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickmorty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rickmorty-app
  template:
    metadata:
      labels:
        app: rickmorty-app
    spec:
      containers:
      - name: rickmorty-app
        image: yishaigalili/rickmorty-app:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5